import Head from "next/head";
import card from '@/styles/card.module.scss';
import { useEffect, useRef } from "react";
import Image from "next/image";
import { useRouter } from "next/router";

const Enemies = ()=> {

    const router = useRouter();
    const query = router.query;

    const dataID = query.data as string;
    const id = parseInt(dataID);

    const data = [

        { 
        name:"Alien Scum",
        img:"/assets/black-alien-scum.png",
        text:"Ninja Killer dont touch him"
        },

        {
        name:"Death Smokie",
        img:"/assets/death-smokie.png",
        text:"Ninja Killer dont touch him"
        },

        {
        name:"Ping Pang",
        img:"/assets/angry-ping.png",
        text:"Just som penguin Shit"
        }

    ]

    console.log(data[id]);

    



    return(

        <>
        <Head>
          <title>Black Alien Scum</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
  
        <section id={card.cardContainer}>

          <div id={card.cardContent}>

            <div id={card.headline}>
                {data[id].name}
            </div>

            <div id={card.imagecon}>
                <Image 
                src={data[id].img}
                alt="Picture"
                width={250}
                height={250}
                
                />
            </div>
            <div id={card.content}>
                {data[id].text}
            </div>

          </div>
  
        </section>
         
        </main>
      </>

    )
}

export default Enemies;