import Head from 'next/head';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import card from '@/styles/card.module.scss';





export default function Home() {

  const [count, setCount] = useState<number>(0);

  useEffect( ()=>{
    console.log("poul")
  }, [count])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      <section id={card.cardContainer}>

        <div id={card.cardContent}>pop</div>

      </section>
       
      </main>
    </>
  )
}
